### ISSUE TITLE
Icon Facebook footer quá to và đổi lại ngôn ngữ ở footer là tiếng Việt

### ISSUE THREAD

**Issue by hinerumasato** [nphuonha2101/BookStore_Software-Engineering#18]
**Icon của facebook khá to so với footer, nên điều chỉnh lại**
**Đồng thời đổi ngôn ngữ của footer là tiếng Việt**
![image](https://github.com/nphuonha2101/BookStore_Software-Engineering/assets/117988838/128cdd4e-1bed-47ef-afe6-c541fbdfe8aa)

**Comment by hinerumasato** [comment]
Đề xuất đổi kích thước ảnh là 190x190 pixels

**Comment by hinerumasato** [comment]
Đề xuất thêm opacity cho footer, giá trị là 0.7
background-color: rgba(0, 0, 0, 0.7)

**Comment by nphuonha2101** [comment]
Đã rõ

**Comment by nphuonha2101** [comment]
Đã khắc phục Issues #18
