### ISSUE TITLE
Tạo cơ sở dữ liệu

### ISSUE THREAD

**Issue by hinerumasato** [nphuonha2101/BookStore_Software-Engineering#19]
Các bảng dự kiến cần tạo:
users: id*, email, password, fullname, ...
books: id*, title, content, description, ....
categories: id*, name, ...

**Yêu cầu sau khi tạo thì thêm sẵn một số data (có thể tham khảo [JavaFaker](https://www.baeldung.com/java-faker))**
**Export data thành một file sql duy nhất và lưu vào trong pakage /resources/db/data.sql. Package resources là cấp con trực tiếp của bookstore, nằm cùng cấp với webapp, controllers, configs, ....**

_Có thể tạo thêm bảng nếu cần thiết_

**JavaFaker Basic Usage:**
```
Faker faker = new Faker();

String streetName = faker.address().streetName();
String number = faker.address().buildingNumber();
String city = faker.address().city();
String country = faker.address().country();
```

**Comment by hinerumasato** [comment]
Do your best my friend @nphuonha2101 👍👍 !!!

**Comment by nphuonha2101** [comment]
Đã hoàn thành, dữ liệu được tạo từ JavaFaker nên nhiều dữ liệu sẽ không có nghĩa

**Comment by hinerumasato** [comment]
Ok, đã hiểu
